# Generated by Django 3.1.2 on 2020-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
