# Generated by Django 3.1.2 on 2020-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_wilaya_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='year_in_school',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], default='FRESHMAN', max_length=10),
        ),
    ]
